### ISSUE TITLE
Option to remove shadow in page transition

### ISSUE THREAD

**Issue by afnx** [JonasWanke/swipeable_page_route#16]
First of all, thank you for the awesome package. It works great, but there is something I want to add. This package extends the CupertinoPageRoute class and  CupertinoPageRoute adds a strong shadow to the page transition.

<img width="400" alt="shadow" src="https://user-images.githubusercontent.com/12843244/122641571-e237ff00-d10e-11eb-8fa6-831319e3d39b.png">

It doesn't look good when your app bar has a background color with opacity. It would be good to have an option to disable it. Or, maybe change it to a slightly visible and widely spreading shadow similar to native iOS apps.

**Comment by boucoding** [comment]
Looking forward to find a solution for this

**Comment by JonasWanke** [comment]
This shadow currently originates from [`CupertinoPageTransition`](https://api.flutter.dev/flutter/cupertino/CupertinoPageTransition-class.html) (https://github.com/flutter/flutter/blob/f4abaa0735eba4dfd8f33f73363911d63931fe03/packages/flutter/lib/src/cupertino/route.dart#L472-L479), which uses `_CupertinoEdgeShadowDecoration.kTween` defined here: https://github.com/flutter/flutter/blob/f4abaa0735eba4dfd8f33f73363911d63931fe03/packages/flutter/lib/src/cupertino/route.dart#L783.

Probably the most flexible approach to exposing this would be a new parameter `swipeablePageRoute.pageTransitionBuilder` of the following type:

```dart
Widget Function(
  Animation<double> primaryAnimation,
  Animation<double> secondaryAnimation,
  bool linearTransition,
  Widget child,
)
```

With this, you could then wrap the page in a custom widget instead of the default `CupertinoPageTransition`. This would also allow you to change the animation curves. Would that solution be sufficient for your purposes @afnx @boucoding?

**Comment by boucoding** [comment]
It would be pretty awesome to do.

**Comment by JonasWanke** [comment]
Added in version [v0.2.3](https://pub.dev/packages/swipeable_page_route/changelog#023--2021-08-10)
