### ISSUE TITLE
Named Navigator

### ISSUE THREAD

**Issue by alvazu** [JonasWanke/swipeable_page_route#19]
Hi buddy, is there any way to use this package for named navigation?
Or use like this: 
```dart
MaterialApp(
        theme: ThemeData(
          pageTransitionsTheme: const PageTransitionsTheme(builders: {
            TargetPlatform.iOS: SwipablePageTransitionsBuilder(),
            TargetPlatform.android: SwipablePageTransitionsBuilder(),
          }
)
```

**Comment by JonasWanke** [comment]
Sorry for the delay, this is added in version [v0.2.5](https://pub.dev/packages/swipeable_page_route/changelog#025--2022-01-14). When using the new `SwipeablePageTransitionsBuilder`, it *must* be set for `TargetPlatform.iOS`. For all other platforms, you can decide whether you want to use it. This is because `PageTransitionsTheme` uses the builder for iOS whenever a pop gesture is in progress (https://github.com/flutter/flutter/blob/77d935af4db863f6abd0b9c31c7e6df2a13de57b/packages/flutter/lib/src/material/page_transitions_theme.dart#L595-L596).

Also, note that `context.getSwipeablePageRoute<T>()` doesn't work with this approach as `MaterialPageRoute`s are used instead.
